---
- name: Install dnf-plugins-core
  yum:
    name: dnf-plugins-core
    state: latest
- name: Download podman 
  yum:
    name: "{{ item }}" 
    state: latest
  with_items:
    - podman 
- name: Git clone containers repo
  git:
    repo: 'ssh://git@github.com/ryandamour/containers.git'
    dest: /home/{{ user }}/containers
    ssh_opts: "-o StrictHostKeyChecking=no"
  become: false
- name: Create podman bridge network
  copy:
    src: ../files/87-podman-bridge.conflist
    dest: /etc/cni/net.d/87-podman-bridge.conflist
- name: Disable nftables
  replace:
    path: /etc/firewalld/firewalld.conf
    regexp: 'FirewallBackend=nftables'
    replace: 'FirewallBackend=iptables'
- name: Restart firewalld
  service:
    name: firewalld
    state: restarted
- name: Build all podman images
  podman_image:
    path: /home/{{ user }}/containers/{{ item }}
    name: "{{ user }}" 
    tag: "{{ item }}"
  with_items:
    - "{{ containers }}"
- name: Drop podman binaries
  template:
    src: /home/{{ user }}/containers/services/{{ item }}.j2
    dest: /usr/local/bin/{{ item }}
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ services }}"
