---
- hosts: localhost
  become: true
  tasks:
    - name: Include vars
      include_vars:
        dir: ../vars

    - name: Install neovim
      shell: rpm-ostree install neovim 
      ignore_errors: yes

    - name: Create neovim directory for autoloading configurations
      file:
        path: "/var/home/{{ user }}/.local/share/nvim/site/autoload/"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        recurse: yes
        mode: 0o700

    - name: Install vim-plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "/var/home/{{ user }}/.local/share/nvim/site/autoload/plug.vim"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0o600

    - name: Create base directory for configurations of neovim
      file:
        path: "/var/home/{{ user }}/.config/nvim"
        owner: "{{ user }}"
        group: "{{ user }}"
        state: directory
        mode: 0o700

    - name: Configure neovim
      file:
        src: ../files/init.vim
        dest: "/var/home/{{ user }}/.config/nvim"
        mode: 0o600
        owner: "{{ user }}"
        group: "{{ user }}"
